/*Importamos la base desde un archivo*/

FILENAME REFFILE '/folders/myfolders/1.-Metódos Cuantitativos/BASE_ANECH.xlsx';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLSX
	OUT=BASE_ANECH;
	GETNAMES=YES;
RUN;

/*
PROC UNIVARIATE DATA=BASE_ANECH NORMAL;
VAR EDAD NUTRICION_UNO NUTRICION_DOS
SANIDAD_UNO SANIDAD_DOS SANIDAD_TRES GENETICA_UNO
REPRODUCCION_UNO REPRODUCCION_DOS REPRODUCCION_TRES REPRODUCCION_CUATRO;
*/
PROC UNIVARIATE DATA=BASE_ANECH NORMAL;
VAR EDAD NUTRICION_DOS;
PROC TTEST DATA=BASE_ANECH;
VAR EDAD NUTRICION_DOS;
RUN;